"""empty message

Revision ID: 17f1118847d9
Revises: 
Create Date: 2025-10-14 20:49:02.838333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f1118847d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id_kategori', sa.Integer(), nullable=False),
    sa.Column('nama_kategori', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_kategori')
    )
    op.create_index(op.f('ix_kategori_id_kategori'), 'kategori', ['id_kategori'], unique=False)
    op.create_index(op.f('ix_kategori_nama_kategori'), 'kategori', ['nama_kategori'], unique=False)
    op.create_table('user',
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('alamat', sa.String(), nullable=False),
    sa.Column('no_telp', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('anggota', 'petugas', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id_user'), 'user', ['id_user'], unique=False)
    op.create_index(op.f('ix_user_nama'), 'user', ['nama'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('buku',
    sa.Column('id_buku', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('pengarang', sa.String(), nullable=False),
    sa.Column('penerbit', sa.String(), nullable=False),
    sa.Column('tahun_terbit', sa.Integer(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('id_kategori', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id_kategori'], ),
    sa.PrimaryKeyConstraint('id_buku')
    )
    op.create_index(op.f('ix_buku_id_buku'), 'buku', ['id_buku'], unique=False)
    op.create_index(op.f('ix_buku_judul'), 'buku', ['judul'], unique=False)
    op.create_table('peminjaman',
    sa.Column('id_peminjaman', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('id_petugas', sa.UUID(), nullable=True),
    sa.Column('id_buku', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('tgl_pinjam', sa.DATE(), nullable=False),
    sa.Column('tgl_kembali', sa.DATE(), nullable=True),
    sa.Column('status', sa.Enum('dipinjam', 'dikembalikan', 'hilang', name='statusenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_buku'], ['buku.id_buku'], ),
    sa.ForeignKeyConstraint(['id_petugas'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_peminjaman')
    )
    op.create_index(op.f('ix_peminjaman_id_peminjaman'), 'peminjaman', ['id_peminjaman'], unique=False)
    op.create_table('request_pinjam',
    sa.Column('id_request', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('id_buku', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('tgl_request', sa.DATE(), nullable=False),
    sa.Column('status', sa.Enum('menunggu', 'disetujui', 'ditolak', name='enumrequeststatus'), nullable=False),
    sa.ForeignKeyConstraint(['id_buku'], ['buku.id_buku'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_request')
    )
    op.create_index(op.f('ix_request_pinjam_id_request'), 'request_pinjam', ['id_request'], unique=False)
    op.create_table('pengembalian',
    sa.Column('id_pengembalian', sa.Integer(), nullable=False),
    sa.Column('id_peminjaman', sa.Integer(), nullable=False),
    sa.Column('tgl_kembali', sa.DATE(), nullable=False),
    sa.Column('denda', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['id_peminjaman'], ['peminjaman.id_peminjaman'], ),
    sa.PrimaryKeyConstraint('id_pengembalian')
    )
    op.create_index(op.f('ix_pengembalian_id_peminjaman'), 'pengembalian', ['id_peminjaman'], unique=False)
    op.create_index(op.f('ix_pengembalian_id_pengembalian'), 'pengembalian', ['id_pengembalian'], unique=False)
    op.create_index(op.f('ix_pengembalian_tgl_kembali'), 'pengembalian', ['tgl_kembali'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pengembalian_tgl_kembali'), table_name='pengembalian')
    op.drop_index(op.f('ix_pengembalian_id_pengembalian'), table_name='pengembalian')
    op.drop_index(op.f('ix_pengembalian_id_peminjaman'), table_name='pengembalian')
    op.drop_table('pengembalian')
    op.drop_index(op.f('ix_request_pinjam_id_request'), table_name='request_pinjam')
    op.drop_table('request_pinjam')
    op.drop_index(op.f('ix_peminjaman_id_peminjaman'), table_name='peminjaman')
    op.drop_table('peminjaman')
    op.drop_index(op.f('ix_buku_judul'), table_name='buku')
    op.drop_index(op.f('ix_buku_id_buku'), table_name='buku')
    op.drop_table('buku')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_nama'), table_name='user')
    op.drop_index(op.f('ix_user_id_user'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_kategori_nama_kategori'), table_name='kategori')
    op.drop_index(op.f('ix_kategori_id_kategori'), table_name='kategori')
    op.drop_table('kategori')
    # ### end Alembic commands ###
