"""empty message

Revision ID: 18fd427e6326
Revises: 805e58437ed1
Create Date: 2025-10-08 16:30:36.689268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18fd427e6326'
down_revision: Union[str, Sequence[str], None] = '805e58437ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_pinjam_id_request'), table_name='request_pinjam')
    op.drop_table('request_pinjam')
    op.add_column('RequestPinjam', sa.Column('status', sa.Enum('menunggu', 'disetujui', 'ditolak', name='enumrequeststatus'), nullable=False))
    op.alter_column('peminjaman', 'id_petugas',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peminjaman', 'id_petugas',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('RequestPinjam', 'status')
    op.create_table('request_pinjam',
    sa.Column('id_request', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_buku', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jumlah', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_buku'], ['buku.id_buku'], name=op.f('request_pinjam_id_buku_fkey')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], name=op.f('request_pinjam_id_user_fkey')),
    sa.PrimaryKeyConstraint('id_request', name=op.f('request_pinjam_pkey'))
    )
    op.create_index(op.f('ix_request_pinjam_id_request'), 'request_pinjam', ['id_request'], unique=False)
    # ### end Alembic commands ###
