"""empty message

Revision ID: 67508cb35b80
Revises: 18fd427e6326
Create Date: 2025-10-08 16:32:13.493552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67508cb35b80'
down_revision: Union[str, Sequence[str], None] = '18fd427e6326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requestpinjam_id_request'), table_name='requestpinjam')
    op.drop_table('requestpinjam')
    op.drop_index(op.f('ix_RequestPinjam_id_request'), table_name='RequestPinjam')
    op.drop_table('RequestPinjam')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RequestPinjam',
    sa.Column('id_request', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_buku', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jumlah', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tgl_request', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('menunggu', 'disetujui', 'ditolak', name='enumrequeststatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_buku'], ['buku.id_buku'], name=op.f('RequestPinjam_id_buku_fkey')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], name=op.f('RequestPinjam_id_user_fkey')),
    sa.PrimaryKeyConstraint('id_request', name=op.f('RequestPinjam_pkey'))
    )
    op.create_index(op.f('ix_RequestPinjam_id_request'), 'RequestPinjam', ['id_request'], unique=False)
    op.create_table('requestpinjam',
    sa.Column('id_request', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_buku', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jumlah', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tgl_request', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('menunggu', 'disetujui', 'ditolak', name='enumrequeststatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_buku'], ['buku.id_buku'], name=op.f('requestpinjam_id_buku_fkey')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], name=op.f('requestpinjam_id_user_fkey')),
    sa.PrimaryKeyConstraint('id_request', name=op.f('requestpinjam_pkey'))
    )
    op.create_index(op.f('ix_requestpinjam_id_request'), 'requestpinjam', ['id_request'], unique=False)
    # ### end Alembic commands ###
