"""Revisi Database

Revision ID: 7324ef2bf14d
Revises: 9045abc01662
Create Date: 2025-09-22 20:04:14.765920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7324ef2bf14d'
down_revision: Union[str, Sequence[str], None] = '9045abc01662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peminjaman_id_buku'), table_name='peminjaman')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_peminjaman_id_buku'), 'peminjaman', ['id_buku'], unique=False)
    # ### end Alembic commands ###
