"""init schema

Revision ID: 88dd3518c512
Revises: b935b7b76989
Create Date: 2025-09-18 19:06:11.113607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88dd3518c512'
down_revision: Union[str, Sequence[str], None] = 'b935b7b76989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buku', sa.Column('cover', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buku', 'cover')
    # ### end Alembic commands ###
