"""Revisi Database

Revision ID: 9045abc01662
Revises: 88dd3518c512
Create Date: 2025-09-22 19:56:21.505821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9045abc01662'
down_revision: Union[str, Sequence[str], None] = '88dd3518c512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Drop foreign key lama
    op.drop_constraint('peminjaman_id_anggota_fkey', 'peminjaman', type_='foreignkey')
    op.drop_constraint('peminjaman_id_petugas_fkey', 'peminjaman', type_='foreignkey')

    # 2. Drop table anggota & petugas
    op.drop_index(op.f('ix_anggota_id_anggota'), table_name='anggota')
    op.drop_index(op.f('ix_anggota_nama'), table_name='anggota')
    op.drop_table('anggota')
    op.drop_index(op.f('ix_petugas_id_petugas'), table_name='petugas')
    op.drop_index(op.f('ix_petugas_nama'), table_name='petugas')
    op.drop_table('petugas')

    # 3. Buat table user
    op.create_table(
        'user',
        sa.Column('id_user', sa.Integer(), nullable=False),
        sa.Column('nama', sa.String(), nullable=False),
        sa.Column('alamat', sa.String(), nullable=False),
        sa.Column('no_telp', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('role', sa.Enum('anggota', 'petugas', name='roleenum'), nullable=False),
        sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id_user'), 'user', ['id_user'], unique=False)
    op.create_index(op.f('ix_user_nama'), 'user', ['nama'], unique=False)

    # 4. Ubah peminjaman
    op.drop_column('peminjaman', 'id_anggota')
    op.drop_column('peminjaman', 'jumlah')
    op.drop_column('peminjaman', 'status')

    op.add_column('peminjaman', sa.Column('id_user', sa.Integer(), nullable=False))
    op.create_foreign_key('peminjaman_id_user_fkey', 'peminjaman', 'user', ['id_user'], ['id_user'])
    op.create_foreign_key('peminjaman_id_petugas_fkey', 'peminjaman', 'user', ['id_petugas'], ['id_user'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peminjaman', sa.Column('jumlah', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('peminjaman', sa.Column('id_anggota', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('peminjaman', sa.Column('status', postgresql.ENUM('dipinjam', 'dikembalikan', 'hilang', name='statusenum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'peminjaman', type_='foreignkey')
    op.drop_constraint(None, 'peminjaman', type_='foreignkey')
    op.create_foreign_key(op.f('peminjaman_id_petugas_fkey'), 'peminjaman', 'petugas', ['id_petugas'], ['id_petugas'])
    op.create_foreign_key(op.f('peminjaman_id_anggota_fkey'), 'peminjaman', 'anggota', ['id_anggota'], ['id_anggota'])
    op.create_index(op.f('ix_peminjaman_id_buku'), 'peminjaman', ['id_buku'], unique=False)
    op.drop_column('peminjaman', 'id_user')
    op.create_table('petugas',
    sa.Column('id_petugas', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alamat', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('no_telp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_petugas', name=op.f('petugas_pkey'))
    )
    op.create_index(op.f('ix_petugas_nama'), 'petugas', ['nama'], unique=False)
    op.create_index(op.f('ix_petugas_id_petugas'), 'petugas', ['id_petugas'], unique=False)
    op.create_table('anggota',
    sa.Column('id_anggota', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alamat', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('no_telp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_anggota', name=op.f('anggota_pkey'))
    )
    op.create_index(op.f('ix_anggota_nama'), 'anggota', ['nama'], unique=False)
    op.create_index(op.f('ix_anggota_id_anggota'), 'anggota', ['id_anggota'], unique=False)
    op.drop_index(op.f('ix_user_nama'), table_name='user')
    op.drop_index(op.f('ix_user_id_user'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
