"""init schema

Revision ID: b935b7b76989
Revises: 
Create Date: 2025-09-18 18:40:25.506019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b935b7b76989'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anggota', sa.Column('password', sa.String(), nullable=False))
    op.add_column('petugas', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petugas', 'password')
    op.drop_column('anggota', 'password')
    # ### end Alembic commands ###
