"""empty message

Revision ID: d2e0470a6285
Revises: 9b25e40017dc
Create Date: 2025-10-05 17:21:35.448010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e0470a6285'
down_revision: Union[str, Sequence[str], None] = '9b25e40017dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peminjaman', sa.Column('jumlah', sa.Integer(), nullable=False))
    op.add_column('peminjaman', sa.Column('status', sa.Enum('dipinjam', 'dikembalikan', 'hilang', name='statusenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peminjaman', 'status')
    op.drop_column('peminjaman', 'jumlah')
    # ### end Alembic commands ###
